version: '3.4'

volumes:
  data:
    external: false

services:
  database:
    image: postgres:latest
    volumes:
        - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
    
  hfplay-1:
    depends_on:
      - database
    image: ${DOCKER_REGISTRY-}hfplay
    build:
      context: .
      dockerfile: hfplay/Dockerfile
    environment:
      - ConnectionStrings__Hangfire=Server=database;Port=5432;User Id=postgres;Password=docker;Database=db
#  hfplay-2:
#    depends_on:
#      - database
#    image: ${DOCKER_REGISTRY-}hfplay
#    build:
#      context: .
#      dockerfile: hfplay/Dockerfile
#    environment:
#      - ConnectionStrings__Hangfire=Server=database;Port=5432;User Id=postgres;Password=docker;Database=db
