version: '3.4'

services:
  hfplay-1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
#  hfplay-2:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#     - ASPNETCORE_URLS=http://+:80
#    ports:
#      - "8081:80"
#    volumes:
#      - ~/.aspnet/https:/root/.aspnet/https:ro
#      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro